development:
  adapter: postgresql
  encoding: unicode
  database: sample_development
  pool: 5
  username: postgres
  password: 555
  
test:
  adapter: postgresql
  encoding: unicode
  database: sample_test
  pool: 5
  username: postgres
  password: 555
  
production:
  adapter:	postgresql
  encoding:	unicode
  pool:	5
  database:	d1oll8hqpaditk
  username:	ceipyhahgjfxuk
  password:	U4QALPUhr56J-Qq5XaUtP8Fm_h
  host:	ec2-107-22-164-212.compute-1.amazonaws.com
  port:	5432